In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
import pickle  # Import pickle module

In [3]:
crop = pd.read_csv("Crop_recommendation.csv")
crop

,Nitrogen,phosphorus,potassium,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee

In [4]:
x = crop.drop('label', axis=1)
y = crop['label']

In [5]:
crop.dropna(inplace=True)
crop

,Nitrogen,phosphorus,potassium,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee

In [6]:
lb = LabelEncoder()
crop['label'] = lb.fit_transform(crop['label'])
crop

,Nitrogen,phosphorus,potassium,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,20
1,85,58,41,21.770462,80.319644,7.038096,226.655537,20
2,60,55,44,23.004459,82.320763,7.840207,263.964248,20
3,74,35,40,26.491096,80.158363,6.980401,242.864034,20
4,78,42,42,20.130175,81.604873,7.628473,262.717340,20
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,5
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,5
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,5
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,5
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,5

In [7]:
x = crop.drop('label', axis=1)
y = crop['label']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=0)

In [9]:
classifier = RandomForestClassifier(n_estimators=10, criterion="entropy")
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [10]:
x_pred = classifier.predict(x_train)
y_pred = classifier.predict(x_test)

In [11]:
mean = mean_squared_error(y_train, x_pred)
r2 = r2_score(y_train, x_pred) * 100
print("Train Mean Squared Error:", mean)
print("Train R^2 Score:", r2)

Train Mean Squared Error: 0.0
Train R^2 Score: 100.0

In [12]:
mean = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Test Mean Squared Error:", mean)
print("Test R^2 Score:", r2)

Test Mean Squared Error: 3.0926136363636365
Test R^2 Score: 0.9230368463925864

In [13]:
pred = classifier.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print("Test Accuracy:", ac * 100)

Test Accuracy: 97.2159090909091

In [14]:
# Save the model using pickle
with open("classifier.pkl", "wb") as model_file:
    pickle.dump(classifier, model_file)

In [15]:
# Load the model using pickle
with open("classifier.pkl", "rb") as model_file:
    loaded_classifier = pickle.load(model_file)

In [16]:
test_pred = loaded_classifier.predict([[90, 42, 43, 20.879744, 82.002744, 6.502985, 202.935536]])
print("Test Prediction:", test_pred)

Test Prediction: [20]

c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(