In [2]:
import numpy as np
import pandas as pd

In [3]:
soil = pd.read_csv("dataset1.csv")
soil

,N,P,K,pH,EC,OC,S,Zn,Fe,Cu,Mn,B,Output
0,138,8.6,560,7.46,0.62,0.70,5.90,0.24,0.31,0.77,8.71,0.11,0
1,213,7.5,338,7.62,0.75,1.06,25.40,0.30,0.86,1.54,2.89,2.29,0
2,163,9.6,718,7.59,0.51,1.11,14.30,0.30,0.86,1.57,2.70,2.03,0
3,157,6.8,475,7.64,0.58,0.94,26.00,0.34,0.54,1.53,2.65,1.82,0
4,270,9.9,444,7.63,0.40,0.86,11.80,0.25,0.76,1.69,2.43,2.26,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,351,10.7,623,7.96,0.51,0.29,7.24,0.36,4.69,0.69,11.03,0.69,1
876,264,9.0,486,7.24,0.47,0.10,3.92,0.35,8.26,0.45,7.98,0.40,1
877,276,9.2,370,7.62,0.62,0.49,6.64,0.42,3.57,0.63,6.48,0.32,1
878,320,13.8,391,7.38,0.65,1.07,5.43,0.58,4.58,1.02,13.25,0.53,2
879,264,10.3,475,7.49,0.74,0.88,10.56,0.45,7.36,1.87,10.63,0.63,0

In [4]:
x=soil.drop('Output',axis=1)
x

       N     P    K    pH    EC    OC      S    Zn    Fe    Cu     Mn     B
0    138   8.6  560  7.46  0.62  0.70   5.90  0.24  0.31  0.77   8.71  0.11
1    213   7.5  338  7.62  0.75  1.06  25.40  0.30  0.86  1.54   2.89  2.29
2    163   9.6  718  7.59  0.51  1.11  14.30  0.30  0.86  1.57   2.70  2.03
3    157   6.8  475  7.64  0.58  0.94  26.00  0.34  0.54  1.53   2.65  1.82
4    270   9.9  444  7.63  0.40  0.86  11.80  0.25  0.76  1.69   2.43  2.26
..   ...   ...  ...   ...   ...   ...    ...   ...   ...   ...    ...   ...
875  351  10.7  623  7.96  0.51  0.29   7.24  0.36  4.69  0.69  11.03  0.69
876  264   9.0  486  7.24  0.47  0.10   3.92  0.35  8.26  0.45   7.98  0.40
877  276   9.2  370  7.62  0.62  0.49   6.64  0.42  3.57  0.63   6.48  0.32
878  320  13.8  391  7.38  0.65  1.07   5.43  0.58  4.58  1.02  13.25  0.53
879  264  10.3  475  7.49  0.74  0.88  10.56  0.45  7.36  1.87  10.63  0.63

[880 rows x 12 columns]

In [5]:
y=soil['Output']
y

0      0
1      0
2      0
3      0
4      1
      ..
875    1
876    1
877    1
878    2
879    0
Name: Output, Length: 880, dtype: int64

In [6]:
soil.isnull().sum()

N         0
P         0
K         0
pH        0
EC        0
OC        0
S         0
Zn        0
Fe        0
Cu        0
Mn        0
B         0
Output    0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [8]:
x_train

       N     P    K    pH    EC    OC     S    Zn    Fe    Cu     Mn     B
118  119   8.3  444  7.60  0.76  0.49  7.84  0.41  4.05  2.02   4.85  0.46
12   138   5.3  444  7.68  0.60  0.78  9.70  0.73  0.36  1.32   3.32  2.12
157   88   7.2  391  7.60  0.63  0.29  6.50  0.26  3.66  0.54   8.40  0.08
127  257   6.4  422  7.50  0.59  0.39  5.43  0.28  2.68  1.26  19.21  0.55
443  195   8.1  433  7.53  0.53  0.59  6.33  0.29  8.06  1.22  13.22  0.42
..   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...    ...   ...
835  201   8.3  697  7.48  0.81  0.20  6.64  0.53  5.60  0.86  11.30  0.63
192  169   5.9  338  7.57  0.41  0.65  8.60  0.27  3.15  0.99   9.09  0.19
629  213   9.6  729  7.80  0.49  0.20  4.22  0.37  8.33  0.65  10.25  0.29
559  257  11.2  412  8.00  0.31  1.07  5.43  0.45  6.21  1.32  11.54  0.29
684  320  65.8  528  7.50  0.52  0.49  1.50  0.11  1.14  0.20  13.92  0.29

[616 rows x 12 columns]

In [9]:
y_train

118    0
12     2
157    0
127    0
443    0
      ..
835    0
192    0
629    0
559    0
684    2
Name: Output, Length: 616, dtype: int64

In [10]:
x_test

       N     P    K    pH    EC    OC      S    Zn    Fe    Cu     Mn     B
150  132   8.1  433  7.50  0.51  0.78  26.24  0.33  5.21  3.02   4.52  0.55
406  251   6.4  644  7.12  0.32  0.10   5.43  0.47  3.22  1.93  15.23  0.40
513  270  14.7  465  7.40  0.49  0.10  11.16  0.51  3.64  0.59   9.80  0.32
101  326   6.8  486  7.80  0.82  1.07   4.22  0.58  4.58  0.86  11.52  0.74
535  333  14.9  422  8.26  0.48  1.17   8.45  0.51  3.32  1.08   9.21  0.32
..   ...   ...  ...   ...   ...   ...    ...   ...   ...   ...    ...   ...
52    88   7.2  655  7.46  0.44  1.00  13.10  0.18  0.78  1.03   2.27  1.94
761  326  10.3  507  7.88  0.71  0.10   4.52  0.28  3.02  1.09   7.15  0.67
124  201   6.6  655  7.60  0.64  0.10   6.33  0.41  1.69  1.57  11.05  0.53
573  264   6.1  644  7.60  0.33  0.68   9.95  0.28  3.21  1.87  11.05  0.32
704  370   7.0  528  7.50  0.56  0.73   7.10  0.37  0.74  0.38   1.14  1.35

[264 rows x 12 columns]

In [11]:
y_test

150    0
406    0
513    1
101    1
535    2
      ..
52     2
761    1
124    0
573    0
704    1
Name: Output, Length: 264, dtype: int64

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
classi= RandomForestClassifier(n_estimators= 10, criterion="entropy")

In [14]:
classi.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [15]:
x_pred=classi.predict(x_train)
y_pred=classi.predict(x_test)

In [16]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score

In [17]:
mean=mean_squared_error(y_train,x_pred)
mean*100

0.8116883116883116

In [18]:
r2=r2_score(y_train,x_pred)*100
r2

97.40563852458325

In [19]:
mean=mean_squared_error(y_test,y_pred)*100
mean

13.636363636363635

In [20]:
r2=r2_score(y_test,y_pred)
r2*100

63.388420201086326

In [21]:
pred=classi.predict(x_test)
pred

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1],
      dtype=int64)

In [22]:
pred=classi.predict([[138,8.6,560,7.46,0.62,0.70,5.90,0.24,0.31,0.77,8.71,0.11]])
pred

c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [23]:
ac=accuracy_score(y_test,y_pred)
ac*100

88.63636363636364

In [24]:
import joblib

In [25]:
joblib.dump(classi,"classi.pkl")

['classi.pkl']